version: '3.8'

services:
  app:
    build: .
    container_name: tcc-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tcc
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tcc
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: