security:
  jwt:
    token:
      secret-key: security.jwt.token.secret=${JWT_SECRET:53cr37}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_SECRET}
    password: ${PASSWORD_SECRET}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          mail.debug: true
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      show-sql: false
    open-in-view: false

frontend:
  url: ${FRONTEND_URL:http://localhost:3000}