name: Build, Push Docker Compose Application and Create Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx (for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      # Step 4: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}  # Use secrets para credenciais
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Step 5: Build the Docker image
      - name: Build Docker Image
        run: |
          cd "6 - CÓDIGO BACKEND/repositorio_tcc"
          docker build -t conecta-memory .
      # Step 6: Start Application and Database
      - name: Start Application and Database
        run: |
          cd "6 - CÓDIGO BACKEND"
          docker-compose up -d
      # Step 7: Wait for Database to be Ready
      - name: Wait for Database
        run: |
          echo "Waiting for database to be ready..."
          sleep 30  # Ajuste o tempo conforme necessário
      # Step 8: Run Maven Build inside the Maven Container
      - name: Build Java Project
        run: |
          cd "6 - CÓDIGO BACKEND/repositorio_tcc"
          docker run --rm \
            -v "${{ github.workspace }}/6 - CÓDIGO BACKEND/repositorio_tcc:/app" \
            -w /app \
            maven:3-eclipse-temurin-22-alpine \
            mvn package -DskipTests
      # Step 9: Build and push Docker images using docker-compose
      - name: Build and push Docker images
        run: |
          cd "6 - CÓDIGO BACKEND"
          docker-compose build
          docker-compose push
          
      # Step 10: Check if a release tag exists and increment the version
      - name: Check if release tag exists and increment version
        id: check_release
        run: |
          git fetch --tags
          latest_tag=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          echo "Latest tag: $latest_tag"
          version=$(echo "$latest_tag" | awk -F. '{print $1 "." $2 "." $3+1}')
          echo "New version: $version"
          echo "RELEASE_VERSION=$version" >> $GITHUB_ENV
          echo "exists=false" >> $GITHUB_ENV
      
      # Step 11: Create Release
      - name: Create Release
        id: create_release
        if: env.exists == 'false'
        uses: actions/create-release@v1
        with:
          tag_name: "${{ env.RELEASE_VERSION }}"
          release_name: "Release ${{ env.RELEASE_VERSION }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }} 

      # Step 12: Upload release assets (the built JAR file)
      - name: Upload Release Asset
        if: env.exists == 'false'
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "./6 - CÓDIGO BACKEND/repositorio_tcc/target/repositorioDeTcc-0.0.1-SNAPSHOT.jar"  
          asset_name: "repositorioDeTcc.jar"
          asset_content_type: application/java-archive
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }} 
